# Port for Ride Booking & Trip Lifecycle Microservice
server.port=8083

# Microservice Name (used by API Gateway, OpenFeign, and Eureka)
spring.application.name=ride-service

# In-Memory H2 Database configuration for isolated ridedb
spring.datasource.url=jdbc:h2:mem:ridedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Web Console to inspect rides table at http://localhost:8083/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client Configuration to register with Eureka Service Registry on port 8761
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
